import type { MetadataRoute } from 'next'

const baseUrl = 'https://govtexamsstudy.org'

const QUANT_TOPICS = [
  'percentage',
  'profit-loss',
  'ratio',
  'time-speed-distance',
  'time-work',
  'number-system',
  'average',
  'simple-compound-interest',
  'mixture-alligation',
  'mensuration',
  'algebra',
  'trigonometry',
  'data-interpretation',
  'statistics-probability',
  'surds-indices',
  'partnership',
  'ages',
  'simplification',
  'sequences-series',
  'decimal-fractions',
  'square-cube-roots',
  'chain-rule',
  'boats-streams',
  'problems-on-trains',
  'races-games',
  'calendar',
  'clocks',
  'stocks-shares',
  'true-discount',
  'bankers-discount',
  'logarithms',
]

const REASONING_TOPICS = [
  'seating',
  'syllogism',
  'series',
  'blood-relations',
  'direction-distance',
  'coding-decoding',
  'puzzles',
  'inequalities',
  'analogies',
  'classification',
  'statement-conclusions',
  'input-output',
  'alphabet-tests',
  'cause-effect',
  'order-ranking',
  'data-sufficiency',
  'calendar-reasoning',
  'logical-venn-diagrams',
  'linear-arrangements',
  'critical-reasoning',
  'figure-series',
  'embedded-figures',
  'mirror-water-images',
  'cubes-dice',
  'paper-folding',
  'clock-reasoning',
  'counting-figures',
]

const POLITY_TOPICS = [
  'historical-background',
  'constituent-assembly',
  'preamble',
  'union-territory',
  'citizenship',
  'fundamental-rights',
  'dpsp',
  'fundamental-duties',
  'president-vp',
  'prime-minister',
  'parliament',
  'governor',
  'chief-minister',
  'state-legislature',
  'supreme-court',
  'high-courts',
  'tribunals',
  'centre-state-relations',
  'inter-state-relations',
  'emergency-provisions',
  'amendment-procedure',
  'panchayati-raj',
  'municipalities',
  'election-commission',
  'cag',
  'upsc-spsc',
  'finance-commission',
  'statutory-bodies',
  'anti-defection',
  'scheduled-tribal-areas',
]

const GEOGRAPHY_TOPICS = [
  'physiography',
  'drainage-systems',
  'climate-monsoon',
  'soils',
  'natural-vegetation',
  'biodiversity',
  'islands-coasts',
  'agriculture',
  'irrigation',
  'minerals',
  'energy',
  'industries',
  'transport',
  'population',
  'urbanization',
  'tribes',
  'migration',
  'geomorphology',
  'climatology',
  'oceanography',
  'world-mapping',
  'ecosystems',
  'environmental-pollution',
  'climate-change',
  'protected-areas',
  'biodiversity-conservation',
  'disaster-management',
  'environmental-legislation',
  'water-resources',
  'land-resources',
]

const HISTORY_TOPICS = [
  'indus-valley',
  'vedic-period',
  'buddhism-jainism',
  'mahajanapadas',
  'maurya-empire',
  'post-maurya',
  'sangam-age',
  'gupta-empire',
  'south-indian-dynasties',
  'delhi-sultanate',
  'vijayanagara-bahmani',
  'bhakti-sufi',
  'mughal-empire',
  'maratha-empire',
  'medieval-kingdoms',
  'european-companies',
  'british-expansion',
  'governor-generals',
  'british-economic-policies',
  'revolt-1857',
  'reform-movements',
  'congress-national-movement',
  'gandhian-movements',
  'revolutionary-movement',
  'constitutional-development',
  'tribal-peasant-movements',
  'independence-partition',
  'princely-states',
  'nation-building',
  'wars-foreign-policy',
  'indian-architecture',
  'paintings-sculpture',
  'music-dance',
  'indian-literature',
  'heritage-sites',
]

const ECONOMICS_TOPICS = [
  'basic-concepts',
  'national-income',
  'money-supply',
  'inflation',
  'poverty-unemployment',
  'rbi',
  'banking-system',
  'financial-markets',
  'banking-npas',
  'insurance',
  'union-budget',
  'fiscal-policy',
  'tax-system',
  'public-debt',
  'public-expenditure',
  'foreign-trade',
  'exchange-rate',
  'international-organizations',
  'fdi-fii',
  'planning',
  'economic-reforms',
  'agriculture-economy',
  'industry-policy',
  'infrastructure',
  'inclusive-growth',
  'government-schemes',
  'digital-economy',
  'sustainable-development',
  'social-security',
  'demographic-dividend',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  const staticRoutes = [
    '/',
    '/quant',
    '/quant/geometry',
    '/reasoning',
    '/polity',
    '/polity/articles',
    '/polity/amendments',
    '/polity/landmark-cases',
    '/history',
    '/history/timeline',
    '/history/freedom-movement',
    '/geography',
    '/economics',
    '/economics/flows',
    '/economics/budget',
    '/science',
    '/science/periodic-table',
    '/science/human-body',
    '/practice',
  ]

  const quantRoutes = QUANT_TOPICS.map((slug) => `/quant/${slug}`)
  const reasoningRoutes = REASONING_TOPICS.map((slug) => `/reasoning/${slug}`)
  const polityRoutes = POLITY_TOPICS.map((slug) => `/polity/${slug}`)
  const historyRoutes = HISTORY_TOPICS.map((slug) => `/history/${slug}`)
  const geographyRoutes = GEOGRAPHY_TOPICS.map((slug) => `/geography/${slug}`)
  const economicsRoutes = ECONOMICS_TOPICS.map((slug) => `/economics/${slug}`)

  const allRoutes = [...staticRoutes, ...quantRoutes, ...reasoningRoutes, ...polityRoutes, ...historyRoutes, ...geographyRoutes, ...economicsRoutes]

  return allRoutes.map((route) => {
    const depth = route.split('/').filter(Boolean).length
    return {
      url: `${baseUrl}${route}`,
      lastModified: now,
      changeFrequency: route === '/' ? 'daily' : 'weekly',
      priority: route === '/' ? 1.0 : depth === 1 ? 0.8 : 0.6,
    }
  })
}
